apiVersion: apps/v1
kind: Deployment
metadata:
  name: qa
spec:
  selector:
    matchLabels:
      app: qa
  replicas: 3
  template:
    metadata:
      labels:
        app: qa
    spec:
      containers:
      - name: qa
        image: rokonzaman/django-qa:tagVersion
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: qa-pod-port
---
apiVersion: v1
kind: Service
metadata:
  name: qa
  labels:
    app: qa
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: qa-pod-port
    nodePort: 31114
    protocol: TCP
  selector:
    app: qa
